### ISSUE TITLE
train error 

### ISSUE THREAD

**Issue by nagexiaochengzi** [xz-pisces/DGarment#5]
ValueError: shapes (6890,3,300) and (10,) not aligned: 300 (dim 2) != 10 (dim 0)
May I ask what caused this?

**Comment by xusongxuliangwangsulong** [comment]
SMPL version ,choose 1.0.0

**Comment by nagexiaochengzi** [comment]
> SMPL 版本，选择 1.0.0

FileNotFoundError: [Errno 2] No such file or directory: '/home/jkx/projects/mjz/DGarment/Data/smpl/model_neutral.pkl'

**Comment by nagexiaochengzi** [comment]
I changed “smpl_path += ‘model_[G].pkl’.replace(‘[G]’, 'neutral ' if gender=='M' else 'neutral)” to ‘smpl_path += ’model_[G].pkl‘.replace(’[G] ') is ok”?

**Comment by nagexiaochengzi** [comment]
Thank you for your excellent work, I just change the version of smpl and it says that model_neutral.pkl is not found, when I move the model_neutral.pkl from version 1.1.0 it says “alueError: shapes (6890,3,300) and (10, ) not aligned: 300 (dim 2) ! ) not aligned: 300 (dim 2) ! = 10 (dim 0)” error, do I still need to change the code content? How can I change it?

**Comment by nagexiaochengzi** [comment]
> SMPL version ,choose 1.0.0

May I ask why this error occurs when I choose version 1.0.0?

**Comment by xusongxuliangwangsulong** [comment]
Download the neutral SMPL model from http://smplify.is.tue.mpg.de/ and place it in the "Data/smpl" folder (Data/smpl/model_f.pkl, Data/smpl/model_neutral.pkl, Data/smpl/model_m.pkl).   
【**"Download version 1.0.0 and then rename it."**】

**Comment by nagexiaochengzi** [comment]
> 从 http://smplify.is.tue.mpg.de/ 下载中性 SMPL 模型，并将其放在“Data/smpl”文件夹（Data/smpl/model_f.pkl、Data/smpl/model_neutral.pkl、Data/smpl/model_m.pkl）中。 【**下载 1.0.0 版本，然后重命名它。**】

Thanks for your answer, but now “dirt” has error “AttributeError: module ‘dirt’ has no attribute ‘lighting’”, my pytorch version is 1.7.1, does the project have requirements for the torch version?My GPU is a Tesla-V100,any hardware requirements?Is the cuda version 10.1?
